create table cart_item (
    id BIGINT generated by default as identity primary key ,
    users_id BIGINT NOT NULL,
    product_id BIGINT not null,
    quantity INTEGER not null,
    price DOUBLE not null,

    constraint fk_cart_user FOREIGN KEY (users_id) references users(id),
    constraint fk_cart_product foreign key (product_id) references product(id)
)
